# Generated by Django 3.1.3 on 2020-11-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ibsn',
            new_name='isbn',
        ),
    ]
